[theme]
primaryColor = "#4B61AC"
backgroundColor = "#1E1E2E"
secondaryBackgroundColor = "#2A2A3C"
textColor = "#FAFAFA"
font = "sans serif"

[server]
enableCORS = true
enableXsrfProtection = true

[browser]
gatherUsageStats = false
